### ISSUE TITLE
Maven central release?

### ISSUE THREAD

**Issue by m50d** [jcouyang/owlet#1]
Hi, I'd like to be able to release my owlet-using project to maven central (if only to be able to use the webjars CDN). Are you willing to make a release to maven central? Or I can make my own fork and release there?

**Comment by jcouyang** [comment]
feel free to do so, if you can release to maven that would be perfect, I was trying to release it to sonatype from sbt but endup with struggling with gpg, will revisit it while i'm free.

**Comment by m50d** [comment]
Ah I hadn't noticed it was SBT, I've only even been able to release with maven.

**Comment by m50d** [comment]
Hi again,

I made a maven build so that I can do this, since I've done that before and know how it works.

1. What's the license? (I know maven central requires that to be set before they accept)
2. I assume you're happy for me to put your name and email as developer?
3. Should I PR my fork to your repository? I'm happy to treat my fork as just a temporary throwaway thing for until you get releases working with SBT. I don't think it's a good idea to have two sets of build configurations running in the long term, but I assume you wouldn't want to move to maven?

**Comment by jcouyang** [comment]
1. MIT
2. sure
3. PR please
thanks

**Comment by jcouyang** [comment]
I just tried new version of sbt again, it seems the gpg isssue was resolved, I'll try release it to sonatype again and keep you in loop

**Comment by jcouyang** [comment]
thanks @m50d I just released to sonatype, it will be sync to mvn soon I think
https://oss.sonatype.org/content/groups/public/us/oyanglul/owlet_sjs0.6_2.12/0.1.5/

**Comment by m50d** [comment]
Yep I see it in Maven central now. Many thanks.
