### ISSUE TITLE
label is not labeling properly

### ISSUE THREAD

**Issue by cryptokoans** [jcouyang/owlet#7]
Being able to label components is really nice! However I noticed that the labeling stopped working. It could be because the actual string argument for the label is not actually used? See: https://github.com/jcouyang/owlet/blob/master/src/main/scala/owlet/DOM.scala#L264

**Comment by cryptokoans** [comment]
for reference, the example here (taken from the tutorials page) does not actually show the word "Language" anywhere which is supposed to be labeling the select box. https://scalafiddle.io/sf/KNF9u9P/0

**Comment by jcouyang** [comment]
good catch, that should be a bug, I think it supposed to be
```scala
createContainer[A, html.Label]("label", text(textValue) &> inner, className, id)
```
thanks
